//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuzzardWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("offlinecache.db3")]
        public string CacheFileName {
            get {
                return ((string)(this["CacheFileName"]));
            }
            set {
                this["CacheFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mprptq3v")]
        public string DMSPwd {
            get {
                return ((string)(this["DMSPwd"]));
            }
            set {
                this["DMSPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DMS5")]
        public string DMSVersion {
            get {
                return ((string)(this["DMSVersion"]));
            }
            set {
                this["DMSVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTime {
            get {
                return ((bool)(this["FirstTime"]));
            }
            set {
                this["FirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PegasaurusRex")]
        public string InstName {
            get {
                return ((string)(this["InstName"]));
            }
            set {
                this["InstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\proto-5\\BionetXfer\\Run_Complete_Trigger")]
        public string TriggerFileFolder {
            get {
                return ((string)(this["TriggerFileFolder"]));
            }
            set {
                this["TriggerFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyTriggerFiles {
            get {
                return ((bool)(this["CopyTriggerFiles"]));
            }
            set {
                this["CopyTriggerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TurdAlert {
            get {
                return ((bool)(this["TurdAlert"]));
            }
            set {
                this["TurdAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeRequired {
            get {
                return ((bool)(this["SettingsUpgradeRequired"]));
            }
            set {
                this["SettingsUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpgradeWithTestVersion {
            get {
                return ((bool)(this["UpgradeWithTestVersion"]));
            }
            set {
                this["UpgradeWithTestVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTestVersion {
            get {
                return ((bool)(this["IsTestVersion"]));
            }
            set {
                this["IsTestVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownCart {
            get {
                return ((string)(this["FilldownCart"]));
            }
            set {
                this["FilldownCart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownCartConfig {
            get {
                return ((string)(this["FilldownCartConfig"]));
            }
            set {
                this["FilldownCartConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownColumn {
            get {
                return ((string)(this["FilldownColumn"]));
            }
            set {
                this["FilldownColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownComment {
            get {
                return ((string)(this["FilldownComment"]));
            }
            set {
                this["FilldownComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownDatasetType {
            get {
                return ((string)(this["FilldownDatasetType"]));
            }
            set {
                this["FilldownDatasetType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownEMSLProposal {
            get {
                return ((string)(this["FilldownEMSLProposal"]));
            }
            set {
                this["FilldownEMSLProposal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownEMSLUsageType {
            get {
                return ((string)(this["FilldownEMSLUsageType"]));
            }
            set {
                this["FilldownEMSLUsageType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FilldownEMSLUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilldownEMSLUsers"]));
            }
            set {
                this["FilldownEMSLUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownExperimentName {
            get {
                return ((string)(this["FilldownExperimentName"]));
            }
            set {
                this["FilldownExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownInstrument {
            get {
                return ((string)(this["FilldownInstrument"]));
            }
            set {
                this["FilldownInstrument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownInterest {
            get {
                return ((string)(this["FilldownInterest"]));
            }
            set {
                this["FilldownInterest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownOperator {
            get {
                return ((string)(this["FilldownOperator"]));
            }
            set {
                this["FilldownOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownSeparationType {
            get {
                return ((string)(this["FilldownSeparationType"]));
            }
            set {
                this["FilldownSeparationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FillDownWorkPackage {
            get {
                return ((string)(this["FillDownWorkPackage"]));
            }
            set {
                this["FillDownWorkPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherCartName {
            get {
                return ((string)(this["WatcherCartName"]));
            }
            set {
                this["WatcherCartName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherCartConfigName {
            get {
                return ((string)(this["WatcherCartConfigName"]));
            }
            set {
                this["WatcherCartConfigName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherColumn {
            get {
                return ((string)(this["WatcherColumn"]));
            }
            set {
                this["WatcherColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherComment {
            get {
                return ((string)(this["WatcherComment"]));
            }
            set {
                this["WatcherComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherDatasetType {
            get {
                return ((string)(this["WatcherDatasetType"]));
            }
            set {
                this["WatcherDatasetType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherEMSLProposalID {
            get {
                return ((string)(this["WatcherEMSLProposalID"]));
            }
            set {
                this["WatcherEMSLProposalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherEMSLUsageType {
            get {
                return ((string)(this["WatcherEMSLUsageType"]));
            }
            set {
                this["WatcherEMSLUsageType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WatcherEMSLUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WatcherEMSLUsers"]));
            }
            set {
                this["WatcherEMSLUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherExperimentName {
            get {
                return ((string)(this["WatcherExperimentName"]));
            }
            set {
                this["WatcherExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherInstrument {
            get {
                return ((string)(this["WatcherInstrument"]));
            }
            set {
                this["WatcherInstrument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherOperator {
            get {
                return ((string)(this["WatcherOperator"]));
            }
            set {
                this["WatcherOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherSeparationType {
            get {
                return ((string)(this["WatcherSeparationType"]));
            }
            set {
                this["WatcherSeparationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherWorkPackage {
            get {
                return ((string)(this["WatcherWorkPackage"]));
            }
            set {
                this["WatcherWorkPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unreviewed")]
        public string WatcherInterestRating {
            get {
                return ((string)(this["WatcherInterestRating"]));
            }
            set {
                this["WatcherInterestRating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherQCEMSLProposalID {
            get {
                return ((string)(this["WatcherQCEMSLProposalID"]));
            }
            set {
                this["WatcherQCEMSLProposalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherQCEMSLUsageType {
            get {
                return ((string)(this["WatcherQCEMSLUsageType"]));
            }
            set {
                this["WatcherQCEMSLUsageType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WatcherQCEMSLUsers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WatcherQCEMSLUsers"]));
            }
            set {
                this["WatcherQCEMSLUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherQCExperimentName {
            get {
                return ((string)(this["WatcherQCExperimentName"]));
            }
            set {
                this["WatcherQCExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherQCMonitors {
            get {
                return ((string)(this["WatcherQCMonitors"]));
            }
            set {
                this["WatcherQCMonitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchPath {
            get {
                return ((string)(this["SearchPath"]));
            }
            set {
                this["SearchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TopDirectoryOnly")]
        public global::System.IO.SearchOption SearchDirectoryOptions {
            get {
                return ((global::System.IO.SearchOption)(this["SearchDirectoryOptions"]));
            }
            set {
                this["SearchDirectoryOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".raw")]
        public string SearchExtension {
            get {
                return ((string)(this["SearchExtension"]));
            }
            set {
                this["SearchExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SearchMinimumSizeKB {
            get {
                return ((int)(this["SearchMinimumSizeKB"]));
            }
            set {
                this["SearchMinimumSizeKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_MatchFolders {
            get {
                return ((bool)(this["Search_MatchFolders"]));
            }
            set {
                this["Search_MatchFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-01-01")]
        public global::System.DateTime SearchDateFrom {
            get {
                return ((global::System.DateTime)(this["SearchDateFrom"]));
            }
            set {
                this["SearchDateFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2030-01-01")]
        public global::System.DateTime SearchDateTo {
            get {
                return ((global::System.DateTime)(this["SearchDateTo"]));
            }
            set {
                this["SearchDateTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Searcher_IncludeArchivedItems {
            get {
                return ((bool)(this["Searcher_IncludeArchivedItems"]));
            }
            set {
                this["Searcher_IncludeArchivedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Watcher_WaitTime {
            get {
                return ((int)(this["Watcher_WaitTime"]));
            }
            set {
                this["Watcher_WaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WatcherQCCreateTriggerOnDMSFail {
            get {
                return ((bool)(this["WatcherQCCreateTriggerOnDMSFail"]));
            }
            set {
                this["WatcherQCCreateTriggerOnDMSFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WatcherCreateTriggerOnDMSFail {
            get {
                return ((bool)(this["WatcherCreateTriggerOnDMSFail"]));
            }
            set {
                this["WatcherCreateTriggerOnDMSFail"] = value;
            }
        }
    }
}
