//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuzzardWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("offlinecache.db3")]
        public string CacheFileName {
            get {
                return ((string)(this["CacheFileName"]));
            }
            set {
                this["CacheFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoMonitor {
            get {
                return ((bool)(this["AutoMonitor"]));
            }
            set {
                this["AutoMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mprptq3v")]
        public string DMSPwd {
            get {
                return ((string)(this["DMSPwd"]));
            }
            set {
                this["DMSPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateTriggerFiles {
            get {
                return ((bool)(this["CreateTriggerFiles"]));
            }
            set {
                this["CreateTriggerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DMS5")]
        public string DMSVersion {
            get {
                return ((string)(this["DMSVersion"]));
            }
            set {
                this["DMSVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\my documents\\Error")]
        public string ErrorPath {
            get {
                return ((string)(this["ErrorPath"]));
            }
            set {
                this["ErrorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTime {
            get {
                return ((bool)(this["FirstTime"]));
            }
            set {
                this["FirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PegasaurusRex")]
        public string InstName {
            get {
                return ((string)(this["InstName"]));
            }
            set {
                this["InstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\proto-5\\BionetXfer\\Run_Complete_Trigger")]
        public string TriggerFileFolder {
            get {
                return ((string)(this["TriggerFileFolder"]));
            }
            set {
                this["TriggerFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TurdAlert {
            get {
                return ((bool)(this["TurdAlert"]));
            }
            set {
                this["TurdAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m:\\data")]
        public string WatchDirectory {
            get {
                return ((string)(this["WatchDirectory"]));
            }
            set {
                this["WatchDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".MS")]
        public string WatchExtension {
            get {
                return ((string)(this["WatchExtension"]));
            }
            set {
                this["WatchExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteTriggerFiles {
            get {
                return ((bool)(this["WriteTriggerFiles"]));
            }
            set {
                this["WriteTriggerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyTriggerFiles {
            get {
                return ((bool)(this["CopyTriggerFiles"]));
            }
            set {
                this["CopyTriggerFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedInstrument {
            get {
                return ((string)(this["WatcherConfig_SelectedInstrument"]));
            }
            set {
                this["WatcherConfig_SelectedInstrument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedCartName {
            get {
                return ((string)(this["WatcherConfig_SelectedCartName"]));
            }
            set {
                this["WatcherConfig_SelectedCartName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedCartConfigName {
            get {
                return ((string)(this["WatcherConfig_SelectedCartConfigName"]));
            }
            set {
                this["WatcherConfig_SelectedCartConfigName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedSeperationType {
            get {
                return ((string)(this["WatcherConfig_SelectedSeperationType"]));
            }
            set {
                this["WatcherConfig_SelectedSeperationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedColumnData {
            get {
                return ((string)(this["WatcherConfig_SelectedColumnData"]));
            }
            set {
                this["WatcherConfig_SelectedColumnData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_SelectedOperator {
            get {
                return ((string)(this["WatcherConfig_SelectedOperator"]));
            }
            set {
                this["WatcherConfig_SelectedOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Watcher_WatchDir {
            get {
                return ((string)(this["Watcher_WatchDir"]));
            }
            set {
                this["Watcher_WatchDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TopDirectoryOnly")]
        public global::System.IO.SearchOption Watcher_SearchType {
            get {
                return ((global::System.IO.SearchOption)(this["Watcher_SearchType"]));
            }
            set {
                this["Watcher_SearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".raw")]
        public string Watcher_FilePattern {
            get {
                return ((string)(this["Watcher_FilePattern"]));
            }
            set {
                this["Watcher_FilePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Watcher_WaitTime {
            get {
                return ((int)(this["Watcher_WaitTime"]));
            }
            set {
                this["Watcher_WaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WatcherConfig_CreateTriggerOnDMS_Fail {
            get {
                return ((bool)(this["WatcherConfig_CreateTriggerOnDMS_Fail"]));
            }
            set {
                this["WatcherConfig_CreateTriggerOnDMS_Fail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_ExperimentName {
            get {
                return ((string)(this["WatcherConfig_ExperimentName"]));
            }
            set {
                this["WatcherConfig_ExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_LCColumn {
            get {
                return ((string)(this["WatcherConfig_LCColumn"]));
            }
            set {
                this["WatcherConfig_LCColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Searcher_IncludeArchivedItems {
            get {
                return ((bool)(this["Searcher_IncludeArchivedItems"]));
            }
            set {
                this["Searcher_IncludeArchivedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QC_ExperimentName {
            get {
                return ((string)(this["QC_ExperimentName"]));
            }
            set {
                this["QC_ExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QC_SelectedUsageType {
            get {
                return ((string)(this["QC_SelectedUsageType"]));
            }
            set {
                this["QC_SelectedUsageType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QC_ProposalID {
            get {
                return ((string)(this["QC_ProposalID"]));
            }
            set {
                this["QC_ProposalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QC_CreateTriggerOnDMS_Fail {
            get {
                return ((bool)(this["QC_CreateTriggerOnDMS_Fail"]));
            }
            set {
                this["QC_CreateTriggerOnDMS_Fail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Watcher_EMSL_UsageType {
            get {
                return ((string)(this["Watcher_EMSL_UsageType"]));
            }
            set {
                this["Watcher_EMSL_UsageType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Watcher_EMSL_ProposalID {
            get {
                return ((string)(this["Watcher_EMSL_ProposalID"]));
            }
            set {
                this["Watcher_EMSL_ProposalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Watcher_EMSL_Users {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Watcher_EMSL_Users"]));
            }
            set {
                this["Watcher_EMSL_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection QC_EMSL_Users {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QC_EMSL_Users"]));
            }
            set {
                this["QC_EMSL_Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownOperator {
            get {
                return ((string)(this["FilldownOperator"]));
            }
            set {
                this["FilldownOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownDatasetType {
            get {
                return ((string)(this["FilldownDatasetType"]));
            }
            set {
                this["FilldownDatasetType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownSeparationType {
            get {
                return ((string)(this["FilldownSeparationType"]));
            }
            set {
                this["FilldownSeparationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownColumn {
            get {
                return ((string)(this["FilldownColumn"]));
            }
            set {
                this["FilldownColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownInstrument {
            get {
                return ((string)(this["FilldownInstrument"]));
            }
            set {
                this["FilldownInstrument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownCart {
            get {
                return ((string)(this["FilldownCart"]));
            }
            set {
                this["FilldownCart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownInterest {
            get {
                return ((string)(this["FilldownInterest"]));
            }
            set {
                this["FilldownInterest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownEMSLUsage {
            get {
                return ((string)(this["FilldownEMSLUsage"]));
            }
            set {
                this["FilldownEMSLUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownEMSLProposal {
            get {
                return ((string)(this["FilldownEMSLProposal"]));
            }
            set {
                this["FilldownEMSLProposal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownExperimentName {
            get {
                return ((string)(this["FilldownExperimentName"]));
            }
            set {
                this["FilldownExperimentName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownComment {
            get {
                return ((string)(this["FilldownComment"]));
            }
            set {
                this["FilldownComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchPath {
            get {
                return ((string)(this["SearchPath"]));
            }
            set {
                this["SearchPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TopDirectoryOnly")]
        public global::System.IO.SearchOption SearchDirectoryOptions {
            get {
                return ((global::System.IO.SearchOption)(this["SearchDirectoryOptions"]));
            }
            set {
                this["SearchDirectoryOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchExtension {
            get {
                return ((string)(this["SearchExtension"]));
            }
            set {
                this["SearchExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2014-01-01")]
        public global::System.DateTime SearchDateFrom {
            get {
                return ((global::System.DateTime)(this["SearchDateFrom"]));
            }
            set {
                this["SearchDateFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2030-01-01")]
        public global::System.DateTime SearchDateTo {
            get {
                return ((global::System.DateTime)(this["SearchDateTo"]));
            }
            set {
                this["SearchDateTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Setting {
            get {
                return ((global::System.DateTime)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Watcher_FileSize {
            get {
                return ((int)(this["Watcher_FileSize"]));
            }
            set {
                this["Watcher_FileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatcherConfig_UserComment {
            get {
                return ((string)(this["WatcherConfig_UserComment"]));
            }
            set {
                this["WatcherConfig_UserComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SearchMinimumSizeKB {
            get {
                return ((int)(this["SearchMinimumSizeKB"]));
            }
            set {
                this["SearchMinimumSizeKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_MatchFolders {
            get {
                return ((bool)(this["Search_MatchFolders"]));
            }
            set {
                this["Search_MatchFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Watcher_MatchFolders {
            get {
                return ((bool)(this["Watcher_MatchFolders"]));
            }
            set {
                this["Watcher_MatchFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilldownCartConfig {
            get {
                return ((string)(this["FilldownCartConfig"]));
            }
            set {
                this["FilldownCartConfig"] = value;
            }
        }
    }
}
